### ISSUE TITLE
没有记住插件地址

### ISSUE THREAD

**Issue by AoEiuV020** [liuxian496/iceborne#13]
每次启动插件地址都是空的， 音量也是默认的， 
是没有记住修改内容吗，还是保存出了什么问题， 看日志好像有一些error，

```


> iceborne@1.4.2 start
> ts-node ./.erb/scripts/check-port-in-use.js && npm run start:renderer


> iceborne@1.4.2 start:renderer
> cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack serve --config ./.erb/configs/webpack.config.renderer.dev.ts

Starting preload.js builder...
Starting Main Process...
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:1212/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.2.45:1212/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::1]:1212/
<i> [webpack-dev-server] Content not from webpack is served from '/Volumes/IAPFS/home/git/iceborne/public' directory
<i> [webpack-dev-server] 404s will fallback to '/index.html'

> iceborne@1.4.2 start:preload
> cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.preload.dev.ts


> iceborne@1.4.2 start:main
> cross-env NODE_ENV=development electronmon -r ts-node/register/transpile-only .

[electronmon] waiting for a change to restart it
2024-06-15 13:52:14.150 Electron[55277:23935232] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
13:52:14.266 › Skip checkForUpdates because application is not packed and dev update config is not forced
13:52:14.268 › checkForUpdatesAndNotify called, downloadPromise is null
<i> [webpack-dev-middleware] wait until bundle finished: /index.html
IPC test: ping
ready-to-show
sent barrage-speaking-change
sent barrage-speaking-change
[55277:0615/135215.575900:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Failed to fetch", source: devtools://devtools/bundled/panels/elements/elements.js (1)
[55277:0615/135215.721866:ERROR:CONSOLE(2)] "Electron sandboxed_renderer.bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (2)
[55277:0615/135215.721915:ERROR:CONSOLE(2)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (2)
2024-06-15 13:52:17.112 Electron[55277:23935232] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
{
  cloudSource: 'blc',
  pluginUrl: 'https://openlivechat.xuehusang.cn/room/open-live?Code=**********&Mid=6483416&Timestamp=1718430027&CodeSign=8f7043317a0972f5bdf78ff0b45be54ba8c7178af6d84f2dec238a8247749af3&skin=none&minGiftPrice=0&minTickerPrice=0.1&showDanmaku=true&showTranslateDanmakuOnly=false&translationSign=%E3%80%90&showSuperchat=true&showNewMember=true&showGift=true&showGiftInfo=true&mergeSimilarDanmaku=false&mergeGift=true&danmakuAtBottom=true&tickerAtButtom=false&maxNumber=30&fadeOutNum=3&pinTime=0&showLike=false&userBlur=false&imageShowType=2&maxImage=2&blockGiftDanmaku=true&blockLevel=0&blockNewbie=false&blockNotMobileVerified=false&blockKeywords=&blockUsers=&blockMedalLevel=0&minDanmakuInterval=400&maxDanmakuInterval=1200&relayMessagesByServer=false&autoTranslate=false&giftUsernamePronunciation=&emoticonSize=80&maskOpacity=10&delayTime=0',
  speech: true,
  volume: 20
}
2024-06-15 13:52:18.865 Electron[55277:23935232] NSWindow does not support nonactivating panel styleMask 0x80
2024-06-15 13:52:18.869 Electron[55277:23935232] NSWindow does not support nonactivating panel styleMask 0x80
[55277:0615/135219.358553:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Failed to fetch", source: devtools://devtools/bundled/panels/elements/elements.js (1)
[55277:0615/135219.477574:ERROR:CONSOLE(2)] "Electron sandboxed_renderer.bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (2)
[55277:0615/135219.477599:ERROR:CONSOLE(2)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (2)
13:52:28.543 › Skip checkForUpdates because application is not packed and dev update config is not forced
13:52:28.544 › checkForUpdatesAndNotify called, downloadPromise is null
[55277:0615/135228.602818:ERROR:extensions_browser_client.cc(67)] Extension Error:
  OTR:     false
  Level:   2
  Source:  
  Message: Error handling response: TypeError: Cannot read properties of undefined (reading 'setIcon')
    at background_setExtensionIconAndPopup (chrome-extension://hinnhjiegdibhdhekmfjeifpncdjhofa/build/background.js:1:1158)
    at checkAndHandleRestrictedPageIfSo (chrome-extension://hinnhjiegdibhdhekmfjeifpncdjhofa/build/background.js:1:1542)
    at Array.forEach (<anonymous>)
    at chrome-extension://hinnhjiegdibhdhekmfjeifpncdjhofa/build/background.js:1:1779
  ID:      hinnhjiegdibhdhekmfjeifpncdjhofa
  Type:    RuntimeError
  Context: 
  Stack Trace: 
    {
      Line:     0
      Column:   1
      URL:      
      Function: (anonymous function)
    }
IPC test: ping
ready-to-show
[55277:0615/135228.751865:ERROR:extensions_browser_client.cc(67)] Extension Error:
  OTR:     false
  Level:   2
  Source:  
  Message: Error in event handler: TypeError: Cannot read properties of undefined (reading 'setIcon')
    at background_setExtensionIconAndPopup (chrome-extension://hinnhjiegdibhdhekmfjeifpncdjhofa/build/background.js:1:1158)
    at chrome-extension://hinnhjiegdibhdhekmfjeifpncdjhofa/build/background.js:1:5018
    at chrome-extension://hinnhjiegdibhdhekmfjeifpncdjhofa/build/background.js:1:5081
  ID:      hinnhjiegdibhdhekmfjeifpncdjhofa
  Type:    RuntimeError
  Context: 
  Stack Trace: 
    {
      Line:     0
      Column:   1
      URL:      
      Function: (anonymous function)
    }
sent barrage-speaking-change
sent barrage-speaking-change
[55277:0615/135228.783174:ERROR:extensions_browser_client.cc(67)] Extension Error:
  OTR:     false
  Level:   2
  Source:  
  Message: Error in event handler: TypeError: Cannot read properties of undefined (reading 'setIcon')
    at background_setExtensionIconAndPopup (chrome-extension://hinnhjiegdibhdhekmfjeifpncdjhofa/build/background.js:1:1158)
    at chrome-extension://hinnhjiegdibhdhekmfjeifpncdjhofa/build/background.js:1:5018
    at chrome-extension://hinnhjiegdibhdhekmfjeifpncdjhofa/build/background.js:1:5081
  ID:      hinnhjiegdibhdhekmfjeifpncdjhofa
  Type:    RuntimeError
  Context: 
  Stack Trace: 
    {
      Line:     0
      Column:   1
      URL:      
      Function: (anonymous function)
    }
[55277:0615/135229.055420:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Failed to fetch", source: devtools://devtools/bundled/panels/elements/elements.js (1)
[55277:0615/135229.151527:ERROR:CONSOLE(2)] "Electron sandboxed_renderer.bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (2)
[55277:0615/135229.151547:ERROR:CONSOLE(2)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (2)

```

**Comment by liuxian496** [comment]
这个逻辑是故意设计的，原因如下：
（1）项目的目的是提供一个简易的弹幕播报。是一个纯前端的解决方案，没有服务器端，也不会对用户的本地文件进行读写。所以用户的任何操作都不会被记录和保存，每次关闭，会恢复默认值。
（2）目前没有支持复杂功能的计划

替代方案：
（1）下载代码，打开mainView.tsx
（1）找到对应的表单控件，填写你想要的默认值（defaultValue），运行测试后，重新打包。
这样每次打开，显示的就是你填写的默认值。

**Comment by liuxian496** [comment]
这不是bug，是故意设计的，原因如下：
（1）项目的目的是提供一个简易的弹幕播报。是一个纯前端的解决方案，没有服务器端，也不会对用户的本地文件进行读写。所以用户的任何操作都不会被记录和保存，每次关闭，会恢复默认值。
（2）目前没有支持读写用户本地文件和复杂功能的计划。

替代方案：
（1）下载代码，打开mainView.tsx
（1）找到对应的表单控件，填写你想要的默认值（defaultValue），运行测试后，重新打包。
这样每次打开，显示的就是你填写的默认值。
